### ISSUE TITLE
Module not found: Error: Can't resolve 'react-create-component-from-tag-prop'

### ISSUE THREAD

**Issue by IljaDaderko** [jameslnewell/styled-components-grid#10]
Unable to run build for some reason, getting 

```
in ./node_modules/styled-components-grid/dist/es/components/Grid.js
Module not found: Error: Can't resolve 'react-create-component-from-tag-prop' in '/Users/ilja/Documents/Repositories/loot-web-app/node_modules/styled-components-grid/dist/es/components'
 @ ./node_modules/styled-components-grid/dist/es/components/Grid.js 7:0-78
 @ ./node_modules/styled-components-grid/dist/es/components/index.js
 @ ./node_modules/styled-components-grid/dist/es/index.js

```

I think it is related to `Couldn't find package "tradie-template-react-component" on the "npm" registry.` error when installing `react-create-component-from-tag-prop` on its own

this is on preview 15

**Comment by jameslnewell** [comment]
Yeah sorry, `tradie-template-react-component` is a private package i haven't released yet and which I've been linking for development. I'll try and get it released :)

Feel free to hack it and PR it and I can check the tests pass etc locally until then.
