### ISSUE TITLE
Width rounding error add up to >100% and wrap

### ISSUE THREAD

**Issue by lauriejones** [jameslnewell/styled-components-grid#7]
Hey James!

Came across a possible bug. The following renders with the last `Grid.Unit` wrapping below and widths that total 101% _(42%, 17%, 42%)_.

```
<Grid>
  <Grid.Unit width={5/12}>Awesome!</Grid.Unit>
  <Grid.Unit width={1/6}>Amazing!</Grid.Unit>
  <Grid.Unit width={5/12}}>Out of this world!</Grid.Unit>
</Grid>
```

Looks like just a rounding issue.

**Comment by jameslnewell** [comment]
👋 Hey mate! I happened to be playing around with it this afternoon while stuck on a train. Can you please check out `styled-components-grid@1.0.0-preview.13` and let me know if its still an issue.  I'm keen to drop the `preview` too so let me know if you find any issues! https://jameslnewell.github.io/styled-components-grid/

**Comment by lauriejones** [comment]
https://github.com/jameslnewell/styled-components-grid/blob/master/src/mixins/grid.js#L10

Needs to be `nowrap` (one word).

But yes, that fixes it 👍  

Nice work on the site man! Looks great. Very Styled Components :slightly_smiling_face:

**Comment by lauriejones** [comment]
Making `Grid.Unit` `display:flex` and `flex-direction: column` by default is a breaking change from earlier previews. (Broke our new [HeroPanel](https://design.nib.com.au/language/master/#/molecule/hero-panel) 😢 )

Is that going to stick around? Are there going to be any other breaking changes before the `1.0.0` release?

**Comment by jameslnewell** [comment]
ah bummer, i'll revert that. i did that to try and make `visibility` work better. if you change the default `display:`, and use visibility, you lose you `display:` value when you make it visible again at a higher breakpoint. got any ideas on how to solve that?

**Comment by jameslnewell** [comment]
try `styled-components-grid@1.0.0-preview.15`

**Comment by lauriejones** [comment]
Works great 😁
