### ISSUE TITLE
Grid always wraps

### ISSUE THREAD

**Issue by lauriejones** [jameslnewell/styled-components-grid#8]
Setting `wrap={false}` does nothing?

Should one of these be `flex-wrap: nowrap;`: https://github.com/jameslnewell/styled-components-grid/blob/master/src/Grid.jsx#L16-L18

**Comment by lauriejones** [comment]
Also the defaultProp for wrap is set to true, but the documentation in the readme says it defaults to false.

**Comment by jameslnewell** [comment]
See discussion on PR.
